### ISSUE TITLE
is this a wrong expression ? 

### ISSUE THREAD

**Issue by FaiScofield** [izhengfan/se2lam#10]
https://github.com/izhengfan/se2lam/blob/0a4f55ab5afd5da541c0a15c97d9d093bb2df7f9/src/MapPoint.cpp#L134

Should it be  `if(pKF_->mIdKF < pKF0->mIdKF) `  ?

**Comment by izhengfan** [comment]
Yes you're right. Thanks. I have fixed it https://github.com/izhengfan/se2lam/commit/ec054e5b749654776060bf6bbb7e0c65ea04b90e
