### ISSUE TITLE
Jacobians in Section III-B(Preintegrated Odometric Constraints)

### ISSUE THREAD

**Issue by hodgechung** [izhengfan/se2lam#11]
I'm confused about the jacobian calculation in Section III-B(Preintegrated Odometric Constraints), could you please write down the whole calculation process for me?
Thank you very much!

**Comment by izhengfan** [comment]
Pls indicate which line you are confused about.

**Comment by hodgechung** [comment]
![2019-10-21 09-43-09屏幕截图](https://user-images.githubusercontent.com/27922189/67171007-9425a200-f3e7-11e9-8774-0312de626cea.png)

**Comment by izhengfan** [comment]
I guess only the first line might be confusing, here is how it works

![image](https://user-images.githubusercontent.com/8697363/68064707-e0fb6800-fd59-11e9-8ea3-84c9cf07c5c0.png)

**Comment by hodgechung** [comment]
Got it, thanks!
