### ISSUE TITLE
Wrong formula

### ISSUE THREAD

**Issue by FaiScofield** [izhengfan/se2lam#12]
https://github.com/izhengfan/se2lam/blob/ec054e5b749654776060bf6bbb7e0c65ea04b90e/src/ORBmatcher.cpp#L157

It should be:
```
const float factor = HISTO_LENGTH / 360.f; 
```
Since "HISTO_LENGTH = 30", the difference angle of two KeyPoints will distributed in 30 regions with 12 degrees per region. 
This code here will result in 30 degrees per region.

**Comment by izhengfan** [comment]
I think you are right. This cpp file is copied from the ORB_SLAM repo, so I guess this bug originates from it.
