### ISSUE TITLE
I get different results on the same dataset

### ISSUE THREAD

**Issue by OhHandsome** [izhengfan/se2lam#13]
![Screenshot from 2019-11-27 10-27-56](https://user-images.githubusercontent.com/23100041/69688514-3e889780-1101-11ea-86b8-1fd752bc014d.png)
![Screenshot from 2019-11-27 10-24-38](https://user-images.githubusercontent.com/23100041/69688524-46483c00-1101-11ea-881d-e8f19231e650.png)
![Screenshot from 2019-11-27 10-22-27](https://user-images.githubusercontent.com/23100041/69688530-4a745980-1101-11ea-8fe4-47699511b7a0.png)

**Comment by CrisGao** [comment]
I have the same question, do you have the answer now

**Comment by CrisGao** [comment]
I also encountered the same problem, do you know what caused it now?

**Comment by CrisGao** [comment]
I think the possible reasons can reference to: https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/71
