### ISSUE TITLE
g2o error when GlobalMapper

### ISSUE THREAD

**Issue by Tofupi** [izhengfan/se2lam#16]
I get errors when run GlobalMapper on ARM-V7 like this:
g2o::Cache* g2o::CacheContainer::createCache(const g2o::Cache::CacheKey&)
fatal error in creating cache of type CACHE_SE3_OFFSET
addEdge: FATAL, cannot resolve caches for edge 0x23284c0

it seems something error with CACHE_SE3_OFFSET？can you help me when not busy?
谢谢先

**Comment by izhengfan** [comment]
Have you met this problem on x86 system? I'm afraid I cannot help with ARM-specific problems because I have no experience on ARM platforms.

**Comment by Tofupi** [comment]
Not yet, Thanks, Maybe I'll try Ceres Solver for back_end optimization
