### ISSUE TITLE
Program terminated with signal SIGSEGV, Segmentation fault.

### ISSUE THREAD

**Issue by hhuchen** [izhengfan/se2lam#18]
I run the se2lam on the Ubuntu18.04. The project can be successfully compiled. Then, I run it according your README. It sends the wrong message: Segmentation fault. And I'm sure it doesn't enter the main function when sending wrong message.

**Comment by izhengfan** [comment]
Not sure what causes your problem, it runs normally on my laptop with Ubuntu 1804.
