### ISSUE TITLE
Jacobian formula problem of  'PreEdgeSE2' ?

### ISSUE THREAD

**Issue by FaiScofield** [izhengfan/se2lam#19]
https://github.com/izhengfan/se2lam/blob/f65b502202b6d2be7dbc4b691b6792bde4bfa5c4/include/se2lam/EdgeSE2XYZ.h#L95
 
我计算了好几遍, 也用数值法验算过, 得到这里的值应该是 -1 ?   
看g2o里面'EdgeSE2'也是-1. 还是我哪里搞错了吗?~

**Comment by izhengfan** [comment]
你是对的，我改过来，感谢纠错
