### ISSUE TITLE
关于DatasetRoom中图片和odo数据的时间戳问题

### ISSUE THREAD

**Issue by fbz1993** [izhengfan/se2lam#22]
郑博，你好，updateImg和updateOdo的数据更新完毕后就阻塞，源码处理同一帧的图片和odo数据，但相机频率和里程计频率差距较大，两帧图像间的odo数据您是您是如何处理的，希望您能指点下，谢谢。

**Comment by izhengfan** [comment]
我这个odo数据其实不是按照其传感器单独按原始频率得到的数据，而是由相机触发，每获得一帧图像就获取一个对应的里程计数据。

**Comment by fbz1993** [comment]
> 我这个odo数据其实不是按照其传感器单独按原始频率得到的数据，而是由相机触发，每获得一帧图像就获取一个对应的里程计数据。

明白了，感谢郑博。
