### ISSUE TITLE
How to compare the result with ground truth

### ISSUE THREAD

**Issue by Fukui-Wang** [izhengfan/se2lam#27]

**Comment by izhengfan** [comment]
Try to align the estimated trajectory to the ground-truth one, but I cannot find my script to do that now. You can use evo https://michaelgrupp.github.io/evo/. Just prepare your result to one of its supported format.

**Comment by Fukui-Wang** [comment]
> Try to align the estimated trajectory to the ground-truth one, but I cannot find my script to do that now. You can use evo https://michaelgrupp.github.io/evo/. Just prepare your result to one of its supported format.

OK,THANKS
