### ISSUE TITLE
Dose this system can be used under tracking mode with map already built? 

### ISSUE THREAD

**Issue by YiChenCityU** [izhengfan/se2lam#3]

**Comment by izhengfan** [comment]
We have implemented this function in https://github.com/izhengfan/se2clam, check Localizer.cpp for it.
However, when upgraded to se2lam, Localizer.cpp is not upgraded accordingly due to that I was busy with other stuff.

**Comment by YiChenCityU** [comment]
Thanks a lot.

**Comment by izhengfan** [comment]
Welcome. Would let you know if I update this project at some later time (hope so 😄)
