### ISSUE TITLE
Why does Jacobian calculation only use fx and not fy in optimization

### ISSUE THREAD

**Issue by CrisGao** [izhengfan/se2lam#30]
I found that the Jacobian calculations in the program only involve fx, such as SE(2)-XYZ constrained Jacobian calculations:
**src/EdgeSE2XYZ.cpp/linearizeOplus()**
![image](https://user-images.githubusercontent.com/32894619/90503238-aa27fe80-e181-11ea-9950-5ccdc15fb4ee.png)
and **Thirdparty/g2o/g2o/types/sba/types_six_dof_expmap.cpp/linearizeOplus()**
![image](https://user-images.githubusercontent.com/32894619/90503280-b90eb100-e181-11ea-9aab-6c6fe0f2aad0.png)

**Comment by izhengfan** [comment]
We use only fx because in the early-stage we use the types of g2o, and `g2o::CameraParameters` only has one parameter `focal_length`, i.e. they consider `fx==fy`. This is correct in all the sensors we met with, so we just keep consistent to it.

**Comment by CrisGao** [comment]
I got it,Thank you
