### ISSUE TITLE
请问一下对SE(2)进行扰动的时为什么没有z轴转动的扰动，也没有xy平移的扰动

### ISSUE THREAD

**Issue by TouchDeeper** [izhengfan/se2lam#37]
您好，
请问一下对SE(2)进行扰动的时为什么没有z轴转动的扰动，也没有xy平移的扰动， 看论文只有对x,y轴转动的扰动以及z轴平移的扰动。

**Comment by izhengfan** [comment]
扰动指的是脱离SE(2)的扰动；SE(2)空间内的状态量已经在估计状态里了，不需要扰动

**Comment by TouchDeeper** [comment]
可以理解为这里引入了z=0，绕x,y转动为0的测量值吗

**Comment by izhengfan** [comment]
可以
