### ISSUE TITLE
How to run se3lam?

### ISSUE THREAD

**Issue by WilliamWangPeng** [izhengfan/se2lam#39]
Hi dear experts,       
    Honor to write a letter to you, I want to know what is wrong with the running part?    

Run rviz:

roscd se2lam   --- roscd: No such package/stack 'se2lam'
rosrun rviz rviz -d rviz.rviz  ---- picture on the left
Run se2lam:   ----  picture on the right

rosrun se2lam test_vn PATH_TO_DatasetRoom PATH_TO_ORBvoc.bin

![image](https://user-images.githubusercontent.com/51076736/112751647-a0ad2180-9001-11eb-9c3f-4501fcdbe292.png)

thank you  
best regards  
William

**Comment by izhengfan** [comment]
Hi, you should learn ROS first. Finish the begin level tutorials, then you would know what `build this project as a ROS package` in the README means, and why your commands fail to run.
