### ISSUE TITLE
请问se2lam论文中公式（20）最后一个等号是怎么来的？

### ISSUE THREAD

**Issue by drscopus** [izhengfan/se2lam#43]
![image](https://github.com/izhengfan/se2lam/assets/9296543/ba633db9-2020-4529-bc5a-e1412a3e5cd8)
请见上图中最后一个 ":="右边的
![image](https://github.com/izhengfan/se2lam/assets/9296543/104c5e9b-2706-4768-8859-6a170e8b2ca7)
和公式（19）中
![image](https://github.com/izhengfan/se2lam/assets/9296543/8415c807-a6bd-448a-a37a-ee81b06960fb)
并不相符啊。
谢谢！

**Comment by izhengfan** [comment]
带～和不带～是两种量。
公式19那个下标的量对应的是公式20最左上角那个量。
:=这个符合表示「定义为」，它右边的是量是新定义的量。
