### ISSUE TITLE
SE2扰动

### ISSUE THREAD

**Issue by zzzzxxxx111** [izhengfan/se2lam#45]
非常感谢您的工作，请问代码在哪里可以找到对SE2位姿施加扰动的部分(rot_xy,tran_z)？

**Comment by izhengfan** [comment]
SE2用的是g2o的，需要去翻g2o的VertexSE2的源码

**Comment by izhengfan** [comment]
哦，你说的是SE2之外3个DOF的扰动项，这里归并到EdgeSE2XYZ里了，没有单独的扰动边；有单独扰动边的是一个更早的工作se2clam
