### ISSUE TITLE
demo的数据集中缺少imu数据

### ISSUE THREAD

**Issue by hubing1994** [izhengfan/se2lam#8]
你好，我阅读了您在ICRA2019上的《Visual-Odometric Localization and Mapping for Ground Vehicles Using SE(2)-XYZ Constraints》这篇文章，对这篇内容非常感兴趣。但是在复现您的开源demo时发现一个问题，好像目前的数据集中缺少imu数据，代码系统中直接读取的是一个2D的里程计数据。感觉这部分代码是跟se2clam工程是一样的？想问一下您适配ICRA2019论文的源码何时能开源呢？

**Comment by izhengfan** [comment]
ICRA 2019 的论文就是基于里程计和视觉的，并不使用 IMU。se2lam 相比 se2clam 改进了约束模型，使用的传感器并没变。

**Comment by hubing1994** [comment]
哦哦，不好意思，看到文章中的预计分，以为是加入了imu的紧组合方案，是我误解了。目前您论文中的方案应该只适用于平层的轮式机器人是吧，如果存在从一个平层通过一个平面斜坡到另外一个平层，是否支持呢？

**Comment by izhengfan** [comment]
暂时还不支持
