### ISSUE TITLE
Dataset warehouse 

### ISSUE THREAD

**Issue by Shashika007** [izhengfan/se2lam#9]
Hi @izhengfan , 

Great work! I read your both papers and tried your both repository including your ORB_SLAM2 odometry adaptation with your dataset attached (Dataset Room) in the repository. I wanted to give try with "Dataset warehouse" which you mentioned in your papers. The reason why i wanted to try is to see horizontal faced camera. I tried to create my own dataset using a camera and AMCL pose in "x,y,theta" , so far it did not give me a good results. It would be nice if you share "Dataset warehouse" with our community.  Well appreciated.

Thank you. 

Shashika

**Comment by izhengfan** [comment]
Hi,  I am sorry Dataset Warehouse can not be shared because it comes from one of our partner  companies.

**Comment by Shashika007** [comment]
Hi @izhengfan 

It is okay. Thank you. And one thing, are you using 'millimeters' instead of 'meters' as your odometry linear measurement units ? 

Thank you. 

Shashika

**Comment by izhengfan** [comment]
yes, it is mm

**Comment by Shashika007** [comment]
@izhengfan Thank you.
